blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('new-post/', CreatePostView.as_view(), name='create_post'),
    path('blog/<slug:slug>', post_detail, name='post_detail'),
    path('about', about, name='about'),
    path('', home, name='home'),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
import os
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from autoslug import AutoSlugField #used to generate slug from title


CATEGORY_CHOICES = [
    ('Software Development', 'Software Development'),
    ('Cybersecurity', 'Cybersecurity'),
    ('Tech in Africa', 'Tech in Africa'),
    ('Python', 'Python'),
    ('Django', 'Django'),
    ('JavaScript', 'JavaScript'),
    ('HTML and CSS', 'HTML and CSS'),
    ('Tutorials', 'Tutorials'),
    ('General Tech', 'General Tech'),
    ('Industry-Specific Tech', 'Industry-Specific Tech'),

]

class Category(models.Model):
    title = models.CharField(choices=CATEGORY_CHOICES, max_length=240)
    slug = AutoSlugField(populate_from='title')

    class Meta:
        ordering = ('title',)
        verbose_name_plural = 'Categories'

    def __str__(self) -> str:
        return self.title
    

STATUS_CHOICES = [
    ('complete', 'complete'),
    ('draft', 'draft'),
]

# generating unique file names for image uploads
def post_image_path(instance, filename):
    filename = os.path.basename(slugify(filename))  # remove any directory paths from filename
    return (f'images/{instance.id or 1}/{filename}')

# Create your models here.
class Post(models.Model):
    category = models.ForeignKey(Category, related_name='posts', on_delete=models.CASCADE, default='General Tech')
    title = models.CharField(max_length=240, unique=True)
    body = models.TextField(blank=True)
    slug = AutoSlugField(populate_from='title')
    image = models.ImageField(upload_to='post_image_path', blank=True, max_length=1000)
    status = models.CharField(choices=STATUS_CHOICES, blank=False, default='draft', max_length=15)
    date_created = models.DateField(auto_now_add=True)
    date_edited = models.DateField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    youtube_link = models.URLField(blank=True)

    class Meta:
        ordering = ('-date_created',)

    def __str__(self):
        return str(self.title)
    
    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'slug': self.slug})
    
class Comment(models.Model):
    commentor = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    body = models.TextField(blank=False)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.commentor}\'s comment at {self.date}'
    
class SubComment(models.Model):
    commentor = models.ForeignKey(User, on_delete=models.CASCADE)
    Comment = models.ForeignKey(Comment, related_name='subcomments', on_delete=models.CASCADE)
    body = models.TextField(blank=False)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.commentor}\'s comment at {self.date}'

blog/forms.py
from django import forms

from .models import Comment, SubComment

from ckeditor.widgets import CKEditorWidget
from .models import Post

class PostAdminForm(forms.ModelForm):
    body = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = Post
        fields = '__all__'


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

class SubCommentForm(forms.ModelForm):
    class Meta:
        model = SubComment
        fields = ('body',)

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator 
from django.http import HttpResponse

from slugify import slugify
import random

from .models import *
from .forms import *

# Create your views here.
def home(request):
    posts = Post.objects.all().order_by('-date_created')
    categories = Category.objects.all()
    if posts:
        trend_post = Post.objects.all().order_by('-comments')[0]
        trend_intro = trend_post.body[:250]


        context = {
            'posts': posts,
            'trend_post': trend_post,
            'trend_intro': trend_intro,
            }
        return render(request, 'blog/index.html', context)
    else:
        return render(request, 'blog/index.html')
    
def about(request):
    return render(request, 'blog/about.html')


def post_detail(request, slug):
    post = get_object_or_404(Post, slug=slug)
    categories = Category.objects.all()

    if request.method == 'POST':
        print(request)
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.commentor = request.user
            comment.post = post
            comment.save()

            return redirect('blog:post_detail', slug=slug)

    else:
        form = CommentForm()

    context = {
        'categories': categories,
        'post': post,
        'form': form,
    }

    return render(request, 'blog/post_detail.html', context)


# the code below is to add login_required decorator to class based views
@method_decorator(login_required, name='dispatch')
class CreatePostView(CreateView):
    model = Post
    fields = ['category', 'title', 'body', 'image', 'status']
    template_name = 'create_post.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.slug = slugify(form.instance.title + str(form.instance.id))
        return super().form_valid(form)
    

blog/templates/blog/about.html
{% extends 'base.html' %}

{% block title %}About Me{% endblock %}

{% block content %}    
    <div class="main-wrapper">
	    	    
	    <article class="about-section py-5">
		    <div class="container">
			    <h2 class="title mb-3">About Me</h2>
			    
			    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. </p>
			    <figure><img class="img-fluid" src="assets/images/about-me.jpg" alt="image"></figure>
			    <h5 class="mt-5">About The Blog</h5>
			    <p>Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, quis gravida magna mi a libero. Fusce vulputate eleifend sapien. Vestibulum purus quam, scelerisque ut, mollis sed, nonummy id, metus.</p>
			    <h5 class="mt-5">My Skills and Experiences</h5>
			    <p>Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi.</p>
			    <h5 class="mt-5">Side Projects</h5>
			    <p>Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi.</p>
			    
			    <figure><a href="https://made4dev.com"><img class="img-fluid" src="assets/images/promo-banner.jpg" alt="image"></a></figure>
		    </div>
	    </article><!--//about-section-->
	    
	    <section class="cta-section theme-bg-light py-5">
		    <div class="container text-center">
			    <h2 class="heading">Newsletter</h2>
			    <div class="intro">Welcome to my blog. Subscribe and get my latest blog post in your inbox.</div>
			    <div class="single-form-max-width pt-3 mx-auto">
				    <form class="signup-form row g-2 g-lg-2 align-items-center">
	                    <div class="col-12 col-md-9">
	                        <label class="sr-only" for="semail">Your email</label>
	                        <input type="email" id="semail" name="semail1" class="form-control me-md-1 semail" placeholder="Enter email">
	                    </div>
	                    <div class="col-12 col-md-2">
	                        <button type="submit" class="btn btn-primary">Subscribe</button>
	                    </div>
	                </form><!--//signup-form-->
			    </div><!--//single-form-max-width-->
		    </div><!--//container-->
	    </section>
    </div>
{% endblock %} 

blog/templates/blog/create_post.html
{% extends 'base.html' %}

{% block tite %}New Post{% endblock %}


{% block content %}
<main class="container">
<div class="row g-5">
    <div class="col-md-8">
        <form method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-8 py-2">
                    <p>Category : {{ form.category }}</p>
                </div>
                <div class="col-10">
                    <p>Title : {{form.title}}</p>
                </div>
            </div>
            <div class="row">
                <div class="col-8">
                    {{ form.body }}
                </div>
            </div>
            <div class="row">
                <div class="col-8 py-2">
                    <p>Image : {{ form.image }}</p>
                </div>
                <div class="col-8">
                    <p>Status : {{ form.status }}</p>
                </div>
            </div>
            <button class="btn btn-success" type="submit"> Post </button>
        </form>
    </div>
    {% include 'includes/sidebar.html' %}
</div>
</main>
{% endblock %}

blog/templates/blog/index.html
{% extends 'base.html' %}
{% load custom_filters %}

{% block title %}Home{% endblock %}

{% block content %}

<div class="main-wrapper">
	    
    <section class="cta-section theme-bg-light py-5">
        <div class="container text-center single-col-max-width">
            <h2 class="heading">DevBlog - A Blog Template Made For Developers</h2>
            <div class="intro">Welcome to my blog. Subscribe and get my latest blog post in your inbox.</div>
            <div class="single-form-max-width pt-3 mx-auto">
                <form class="signup-form row g-2 g-lg-2 align-items-center">
                    <div class="col-12 col-md-9">
                        <label class="sr-only" for="semail">Your email</label>
                        <input type="email" id="semail" name="semail1" class="form-control me-md-1 semail" placeholder="Enter email">
                    </div>
                    <div class="col-12 col-md-2">
                        <button type="submit" class="btn btn-primary">Subscribe</button>
                    </div>
                </form>
            </div>
        </div>
    </section>
    
    
    <section class="blog-list px-3 py-5 p-md-5">
        <div class="container single-col-max-width">
            {% for post in posts %}
            <div class="item mb-5">
                <div class="row g-3 g-xl-0">
                    <div class="col-2 col-xl-3">
                        <img class="img-fluid post-thumb " src="{{ post.image.url }}" alt="image">
                    </div>
                    <div class="col">
                        <h3 class="title mb-1"><a class="text-link" href="{% url 'blog:post_detail' slug=post.slug %}">{{ post.title }}</a></h3>
                        <div class="meta mb-1">
                            <span class="date">{{ post.date_created }}</span>
                            <!-- A custome filter was used to calculate the number of minutes to read the text -->
                            <!-- The 1200 comes from 200 words per minutes X 6 letters in a word on average -->
                            <span class="time">{{ post.body|length|divide_by:1200 }} min read</span> 
                            <span class="comment"><a class="text-link" href="#">{{ post.comments.count }} comments</a></span>
                            <span class="badge badge-secondary">{{ post.category.title }}</span>
                        </div>
                        <!--The safe filter was used because the post has html elements for styling-->
                        <!--The exclude_heading filter is a custom filter-->
                        <div class="intro">{{ post.body|slice:":300"|replace_h1|safe}}...</div>
                        <a class="text-link" href="{% url 'blog:post_detail' slug=post.slug %}">Read more &rarr;</a>
                    </div>
                </div>
            </div>
            {% endfor %}

            <div class="item mb-5">
                <div class="row g-3 g-xl-0">
                    <div class="col-2 col-xl-3">
                        <img class="img-fluid post-thumb " src="assets/images/blog/blog-post-thumb-2.jpg" alt="image">
                    </div>
                    <div class="col">
                        <h3 class="title mb-1"><a class="text-link" href="blog-post.html">About Remote Working</a></h3>
                        <div class="meta mb-1"><span class="date">Published 3 months ago</span><span class="time">3 min read</span><span class="comment"><a class="text-link" href="#">26 comments</a></span></div>
                        <div class="intro">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies...</div>
                        <a class="text-link" href="blog-post.html">Read more &rarr;</a>
                    </div><!--//col-->
                </div><!--//row-->
            </div><!--//item-->
            
            <div class="item mb-5">
                <div class="row g-3 g-xl-0">
                    <div class="col-2 col-xl-3">
                        <img class="img-fluid post-thumb" src="assets/images/blog/blog-post-thumb-3.jpg" alt="image">
                    </div>
                    <div class="col">
                        <h3 class="title mb-1"><a class="text-link" href="blog-post.html">A Guide to Becoming a Full-Stack Developer</a></h3>
                        <div class="meta mb-1"><span class="date">Published 2 months ago</span><span class="time">15 min read</span><span class="comment"><a class="text-link" href="#">3 comments</a></span></div>
                        <div class="intro">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies...</div>
                        <a class="text-link" href="blog-post.html">Read more &rarr;</a>
                    </div><!--//col-->
                </div><!--//row-->
            </div><!--//item-->
            
            <div class="item mb-5">
                <div class="row g-3 g-xl-0">
                    <div class="col-2 col-xl-3">
                        <img class="img-fluid post-thumb" src="assets/images/blog/blog-post-thumb-4.jpg" alt="image">
                    </div>
                    <div class="col">
                        <h3 class="title mb-1"><a class="text-link" href="blog-post.html">High Performance JavaScript</a></h3>
                        <div class="meta mb-1"><span class="date">Published 1 month ago</span><span class="time">8 min read</span><span class="comment"><a class="text-link" href="#">12 comments</a></span></div>
                        <div class="intro">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies...</div>
                        <a class="text-link" href="blog-post.html">Read more &rarr;</a>
                    </div><!--//col-->
                </div><!--//row-->
            </div><!--//item-->
            
            
            <div class="item mb-5">
                <div class="row g-3 g-xl-0">
                    <div class="col-2 col-xl-3">
                        <img class="img-fluid post-thumb" src="assets/images/blog/blog-post-thumb-5.jpg" alt="image">
                    </div>
                    <div class="col">
                        <h3 class="title mb-1"><a class="text-link" href="blog-post.html">Learn React in 24 Hours</a></h3>
                        <div class="meta mb-1"><span class="date">Published 2 months ago</span><span class="time">10 min read</span><span class="comment"><a class="text-link" href="#">23 comments</a></span></div>
                        <div class="intro">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies...</div>
                        <a class="text-link" href="blog-post.html">Read more &rarr;</a>
                    </div><!--//col-->
                </div><!--//row-->
            </div><!--//item-->
            
            <div class="item">
                <div class="row g-3 g-xl-0">
                    <div class="col-2 col-xl-3">
                        <img class="img-fluid post-thumb" src="assets/images/blog/blog-post-thumb-6.jpg" alt="image">
                    </div>
                    <div class="col">
                        <h3 class="title mb-1"><a class="text-link" href="blog-post.html">How to Build Desktop Apps with HTML, CSS and JavaScript</a></h3>
                        <div class="meta mb-1"><span class="date">Published 3 months ago</span><span class="time">2 min read</span><span class="comment"><a class="text-link" href="#">1 comment</a></span></div>
                        <div class="intro">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies...</div>
                        <a class="text-link" href="blog-post.html">Read more &rarr;</a>
                    </div><!--//col-->
                </div><!--//row-->
            </div><!--//item-->
            
            <nav class="blog-nav nav nav-justified my-5">
              <a class="nav-link-prev nav-item nav-link d-none rounded-left" href="#">Previous<i class="arrow-prev fas fa-long-arrow-alt-left"></i></a>
              <a class="nav-link-next nav-item nav-link rounded" href="#">Next<i class="arrow-next fas fa-long-arrow-alt-right"></i></a>
            </nav>
            
        </div>
    </section>
</div>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load custom_filters %}

{% block title %} {{ post.title }} {% endblock %}

{% block content %}        
    <div class="main-wrapper">
	    
	    <article class="blog-post px-3 py-5 p-md-5">
		    <div class="container single-col-max-width">
			    <header class="blog-post-header">
				    <h2 class="title mb-2">{{ post.title }}</h2>
                    <div class="meta mb-1">
                        <span class="date">{{ post.date_created }}</span>
                        <!-- A custome filter was used to calculate the number of minutes to read the text -->
                        <!-- The 1200 comes from 200 words per minutes X 6 letters in a word on average -->
                        <span class="time">{{ post.body|length|divide_by:1200 }} min read</span> 
                        <span class="comment"><a class="text-link" href="#">{{ post.comments.count }} comments</a></span>
                        <span class="badge badge-secondary">{{ post.category.title }}</span>
                    </div>
			    </header>
			    
			    <div class="blog-post-body">
				    <figure class="blog-banner">
				        <a href="#"><img class="img-fluid mt-2" src="{{ post.image.url }}" alt="image" width="600", height="400"></a>
				        <figcaption class="mt-2 text-center image-caption">Image : {{ post.title }}</figcaption>
				    </figure>
				    
				    {{ post.body|safe }}

				    <div class="ratio ratio-16x9">
					   <iframe width="560" height="315" src="{{ post.youtube_link }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>					
					</div>
				   
			    </div>
				    
				<div class="blog-comments-section">
					
                </div>			
		    </div><!--//container-->
	    </article>
	    
	    <section class="promo-section theme-bg-light py-5 text-center">
		    <div class="container">
			    <h2 class="title">Promo Section Heading</h2>
			    <p>You can use this section to promote your side projects etc. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. </p>
                <figure class="promo-figure">
			        <a href="https://made4dev.com" target="_blank"><img class="img-fluid" src="assets/images/promo-banner.jpg" alt="image"></a>
			    </figure>
		    </div><!--//container-->
	    </section><!--//promo-section-->
    </div>

    
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en"> 
<head>
    <title>Obert Gwamure's Blog - {% block title %} {% endblock %}</title>
    
    <!-- Meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Django Blog">
    <meta name="author" content="Obert Gwamure">
    
    <!-- FontAwesome JS-->
	<script defer src="{% static 'assets/fontawesome/js/all.min.js' %}"></script>
    
    <!-- Theme CSS -->  
    <link id="theme-style" rel="stylesheet" href="{% static 'assets/css/theme-3.css' %}">
	<link id="theme-style" rel="stylesheet" href="{% static 'assets/css/custom.css' %}">

</head> 

<body>
    
    <header class="header text-center">	    
	    <h1 class="blog-name pt-lg-4 mb-0"><a class="no-text-decoration" href="{% url 'blog:home' %}">Obert Gwamure's blog</a></h1>
        
	    <nav class="navbar navbar-expand-lg navbar-dark" >
           
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div id="navigation" class="collapse navbar-collapse flex-column" >
				<div class="profile-section pt-3 pt-lg-0">
				    <img class="profile-image mb-3 rounded-circle mx-auto" src="assets/images/profile.png" alt="image" >			
					
					<div class="bio mb-3">Hi, my name is Obert Gwamure. Briefly introduce yourself here. You can also provide a link to the about page.<br><a href="{% url 'blog:about' %}">Find out more about me</a></div><!--//bio-->
					<ul class="social-list list-inline py-3 mx-auto">
			            <li class="list-inline-item"><a href="#"><i class="fab fa-twitter fa-fw"></i></a></li>
			            <li class="list-inline-item"><a href="#"><i class="fab fa-linkedin-in fa-fw"></i></a></li>
			            <li class="list-inline-item"><a href="#"><i class="fab fa-github-alt fa-fw"></i></a></li>
			            <li class="list-inline-item"><a href="#"><i class="fab fa-stack-overflow fa-fw"></i></a></li>
			            <li class="list-inline-item"><a href="#"><i class="fab fa-codepen fa-fw"></i></a></li>
			        </ul>
			        <hr> 
				</div>
				
				<ul class="navbar-nav flex-column text-start">
					<li class="nav-item">
					    <a class="nav-link {% if request.path == '/' %}active{% endif %}" href="{% url 'blog:home' %}"><i class="fas fa-home fa-fw me-2"></i>Blog Home <span class="sr-only">(current)</span></a>
					</li>
					<li class="nav-item">
					    <a class="nav-link" href="#"><i class="fas fa-bookmark fa-fw me-2"></i>Developer Portfolio</a>
					</li>
					<li class="nav-item">
					    <a class="nav-link {% if request.path == '/about' %}active{% endif %}"  href="{% url 'blog:about' %}"><i class="fas fa-user fa-fw me-2"></i>About Me</a>
					</li>
				</ul>
				
				<div class="my-2 my-md-3">
				    <a class="btn btn-primary" href="https://themes.3rdwavemedia.com/" target="_blank">Get in Touch</a>
				</div>
			</div>
		</nav>
    </header>
    
        {% block content %}{% endblock %}
	    
	    <footer class="footer text-center py-2 theme-bg-dark">
		   
	        <!--/* This template is free as long as you keep the footer attribution link. If you'd like to use the template without the attribution link, you can buy the commercial license via our website: themes.3rdwavemedia.com Thank you for your support. :) */-->
            <small class="copyright">Designed by <a href="{% url 'blog:about' %}">Obert Gwamure</a> for developers</small>
		   
	    </footer>
          
    <!-- Javascript -->          
    <script src="{% static 'assets/plugins/popper.min.js' %}"></script> 
    <script src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script> 
	 <!-- Custom JS -->
	 <script src="{% static 'assets/js/blog.js' %}s"></script> 
</body>
</html> 